name: flutter_api_ca_ny
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Service Locator to access objects
  get_it: ^7.6.0   

  #State Managment
  flutter_bloc: ^8.1.2       

  #Http client
  dio: ^5.1.2       

   #Dio client generator
  retrofit: ^4.0.1          

  #Load and cahse images  locally
  cached_network_image: ^3.2.3

  #work with json_serializable - Dev dependency
  json_annotation: ^4.8.1

  #Add functional programming to dart - used for Either
  dartz: ^0.10.1

  #To store data locally
  isar: ^3.1.0+1              
  isar_flutter_libs: ^3.1.0+1

  #to compare objects
  equatable: ^2.0.5

  #to check local file path - used in isar
  path_provider: ^2.0.15

  #To check internet connection
  data_connection_checker_tv: ^0.3.5-nullsafety

  ##routing and navigation
  go_router: ^7.0.1

  ###DEV TOOLS###
  logger: ^1.3.0
  bloc_test: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Mock classes during testing
  mockito: ^5.4.0

  #isar code generator
  isar_generator: ^3.1.0+1

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.6.2
  retrofit_generator: ^6.0.0+3
  test: ^1.24.2


flutter:
  uses-material-design: true


#Dev scripts run with flutter_scripts run
#More info and settup: https://pub.dev/packages/flutter_scripts 
scripts:
  clean: flutter clean && flutter pub get
  build_runner: dart pub run build_runner build --delete-conflicting-outputs
  build_runner_watch: dart pub run build_runner watch
